version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: pip
    directories:
      - /flooding/sentinel1_water_extraction
      - /flooding/sentinel2_water_extraction
    schedule:
      interval: daily
