title: Emergency Management Tools
url: https://linz.github.io
baseurl: /emergency-management-tools

remote_theme: linz/github-pages-theme

github:
  - metadata

plugins:
  - jekyll-remote-theme

exclude:
  - .git/
  - .github/
  - .gitignore
  - .idea/
  - CODING.md
  - LICENSE
  - README.md
  - flooding/
  - machine-readable-to-human-readable-date-time/shell.nix
  - machine-readable-to-human-readable-date-time/test
  - nix
  - pyproject.toml
  - python
  - shell.nix
